<?php

namespace ContainerFypqh8k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RsfRns0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RsfRns0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RsfRns0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.8IESKP1', 'get_ServiceLocator_8IESKP1Service', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.dy_oNnm', 'get_ServiceLocator_DyONnmService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.8IESKP1', 'get_ServiceLocator_8IESKP1Service', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.dy_oNnm', 'get_ServiceLocator_DyONnmService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\ProduitController::new' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\ProduitController:new' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
