<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR0mRNro\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR0mRNro/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR0mRNro.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR0mRNro\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR0mRNro\App_KernelDevDebugContainer([
    'container.build_hash' => 'R0mRNro',
    'container.build_id' => '1b955dd2',
    'container.build_time' => 1749453387,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR0mRNro');
