<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOrfhhe3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOrfhhe3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOrfhhe3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOrfhhe3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOrfhhe3\App_KernelDevDebugContainer([
    'container.build_hash' => 'Orfhhe3',
    'container.build_id' => 'bce5b86d',
    'container.build_time' => 1749887309,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOrfhhe3');
