<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMYxp6G6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMYxp6G6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMYxp6G6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMYxp6G6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMYxp6G6\App_KernelDevDebugContainer([
    'container.build_hash' => 'MYxp6G6',
    'container.build_id' => '2f3a4a43',
    'container.build_time' => 1748612154,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMYxp6G6');
